CRS: 32644 # Canada, Calgary CRS TODO: Get it from shp file.
UHI:
  bands:
    brightness: [10, 11]
    radiance: [10,11]
    reflectance: [2, 3, 4, 5, 6, 7]

Global:
    REGION: 'delhi_test'
    UTM :   32643 
    WGS84:  4326 
 